=== SkillsFundingAgency/das-azure-pipelines-tasks/tasks/EnvironmentConfiguration/tests/resource/SFA.DAS.Test.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "properties": {
    "EventsApi": {
      "properties": {
        "BaseUrl": {
          "minLength": 1,
          "type": "string",
          "environmentVariable": "EventsApiBaseUrl"
        },
        "ClientToken": {
          "minLength": 1,
          "type": "string",
          "environmentVariable": "EventsApiClientToken"
        }
      },
      "additionalProperties": false,
      "required": [
        "BaseUrl",
        "ClientToken"
      ],
      "type": "object"
    },
    "PaymentsEnabled": {
      "type": "boolean",
      "environmentVariable": "PaymentsEnabled"
    },
    "PaymentsBool": {
      "type": "boolean",
      "environmentVariable": "PaymentsBool"
    },
    "PaymentsInt": {
      "type": "integer",
      "environmentVariable": "PaymentsInt"
    },
    "PaymentsNumber": {
      "type": "number",
      "environmentVariable": "PaymentsNumber"
    },
    "PaymentsArray": {
      "type": "array",
      "environmentVariable": "PaymentsArray"
    },
    "PaymentsString": {
      "type": "string",
      "environmentVariable": "PaymentsString"
    },
    "PaymentsDefaultValue": {
      "type": "string",
      "default": "default-value",
      "environmentVariable": "PaymentsDefaultValue"
    },
    "PaymentsBlankDefault": {
      "type": "string",
      "default": ""
    }
  },
  "additionalProperties": false,
  "required": [
    "EventsApi",
    "PaymentsEnabled",
    "PaymentsInt"
  ],
  "type": "object"
}

=== SkillsFundingAgency/das-azure-pipelines-tasks/tasks/EnvironmentConfiguration/tests/resource/SFA.DAS.Test.Valid.json
{
    "EventsApi": {
        "BaseUrl": "https://events.test.com",
        "ClientToken": "xxxxxxxxxxlksmdflkm3lkmlkm"
    },
    "PaymentsEnabled": true,
    "PaymentsInt": 1,
    "PaymentsNumber": 1.0,
    "PaymentsArray": [
        "one",
        "two",
        "three"
    ],
    "PaymentsBlankDefault": ""
}
